import assert from "node:assert/strict"
import test from "node:test"
import { createRequire } from "node:module"

const require = createRequire(import.meta.url)
const RulesAdapter = require("../engine/RulesAdapter.js")
const Upstream = require("../third_party/chess.js/upstream/dist/cjs/chess.js")

function rules(fen) {
  const adapter = RulesAdapter.create(fen ? { fen } : {})
  assert.equal(adapter.valid, true, adapter.error?.detail)
  return adapter
}

test("initial position exposes normalized legal moves", () => {
  const adapter = rules()
  const moves = adapter.legalMoves({ verbose: true })
  assert.equal(moves.length, 20)
  assert.deepEqual(moves.find((move) => move.uci === "e2e4"), {
    uci: "e2e4",
    san: "e4",
    from: "e2",
    to: "e4",
    piece: "pawn",
    color: "white",
    captured: null,
    promotion: null,
    flags: ["double-pawn"]
  })
  assert.equal(adapter.board().length, 32)
  assert.equal(adapter.turn(), "white")
})

test("illegal and malformed moves do not mutate state", () => {
  const adapter = rules()
  const before = adapter.fen()
  assert.equal(adapter.commitMove("e2e5").code, "ILLEGAL_MOVE")
  assert.equal(adapter.commitMove("definitely-not-a-move").code, "INVALID_MOVE_FORMAT")
  assert.equal(adapter.fen(), before)
  assert.deepEqual(adapter.history({ format: "san" }), [])
})

test("commit and undo restore exact FEN and notation", () => {
  const adapter = rules()
  const before = adapter.fen()
  const committed = adapter.commitMove("e2e4")
  assert.equal(committed.ok, true)
  assert.equal(committed.move.san, "e4")
  assert.equal(committed.halfmove_clock, 0)
  assert.deepEqual(adapter.history({ format: "uci" }), ["e2e4"])
  const undone = adapter.undo()
  assert.equal(undone.ok, true)
  assert.equal(undone.restored_fen, before)
  assert.equal(adapter.fen(), before)
  assert.equal(adapter.undo().code, "NO_MOVE_TO_UNDO")
})

test("castling is normalized and crossing an attack is rejected", () => {
  const open = rules("r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1")
  assert.ok(open.legalMoves().some((move) => move.uci === "e1g1"))
  assert.ok(open.legalMoves().some((move) => move.uci === "e1c1"))
  const castle = open.commitMove("e1g1")
  assert.equal(castle.ok, true)
  assert.equal(castle.move.san, "O-O")
  assert.deepEqual(castle.move.flags, ["kingside-castle"])

  const attacked = rules("r3kr1r/8/8/8/8/8/8/R3K2R w KQ - 0 1")
  assert.equal(attacked.legalMoves().some((move) => move.uci === "e1g1"), false)
  assert.equal(attacked.commitMove("e1g1").code, "ILLEGAL_MOVE")
  assert.ok(attacked.legalMoves().some((move) => move.uci === "e1c1"))
})

test("en passant is legal only when it does not expose the king", () => {
  const legal = rules("4k3/8/8/3pP3/8/8/8/4K3 w - d6 0 2")
  assert.deepEqual(legal.legalEnPassantMoves().map((move) => move.uci), ["e5d6"])
  const capture = legal.commitMove("e5d6")
  assert.equal(capture.ok, true)
  assert.ok(capture.move.flags.includes("en-passant"))

  const pinned = rules("4r1k1/8/8/3pP3/8/8/8/4K3 w - d6 0 1")
  const before = pinned.fen()
  assert.deepEqual(pinned.legalEnPassantMoves(), [])
  assert.equal(pinned.effectiveEnPassant(), "-")
  assert.equal(pinned.commitMove("e5d6").code, "ILLEGAL_MOVE")
  assert.equal(pinned.fen(), before)
})

test("promotion requires and honors all four choices", () => {
  const fen = "4k3/P7/8/8/8/8/8/4K3 w - - 0 1"
  const pending = rules(fen)
  const response = pending.commitMove("a7a8")
  assert.equal(response.code, "PROMOTION_REQUIRED")
  assert.deepEqual(response.choices, ["queen", "rook", "bishop", "knight"])
  assert.equal(pending.fen(), fen)

  for (const [name, symbol] of Object.entries({ queen: "q", rook: "r", bishop: "b", knight: "n" })) {
    const adapter = rules(fen)
    const promoted = adapter.commitMove({ from: "a7", to: "a8", promotion: name })
    assert.equal(promoted.ok, true)
    assert.equal(promoted.move.uci, `a7a8${symbol}`)
    assert.equal(promoted.move.promotion, name)
  }
})

test("checkmate, stalemate, and dead-position facts stay vendor scoped", () => {
  const mate = rules()
  for (const move of ["f2f3", "e7e5", "g2g4", "d8h4"])
    assert.equal(mate.commitMove(move).ok, true)
  assert.equal(mate.isCheck(), true)
  assert.equal(mate.isCheckmate(), true)
  assert.equal(mate.hasLegalMoves(), false)

  const stalemate = rules("7k/5Q2/6K1/8/8/8/8/8 b - - 0 1")
  assert.equal(stalemate.isStalemate(), true)
  assert.equal(stalemate.isCheck(), false)

  assert.equal(rules("8/8/8/8/8/8/2k5/K7 w - - 0 1").isDeadPositionCandidate(), true)
  assert.equal(rules("8/8/8/8/8/8/2k5/KN6 w - - 0 1").isDeadPositionCandidate(), true)
})

test("SAN disambiguation is generated by the authority", () => {
  const adapter = rules("4k3/8/8/8/8/8/8/1N2KN2 w - - 0 1")
  const sans = adapter.legalMoves()
    .filter((move) => move.piece === "knight" && move.to === "d2")
    .map((move) => move.san)
    .sort()
  assert.deepEqual(sans, ["Nbd2", "Nfd2"])
})

test("FEN and PGN load failures are transactional", () => {
  const adapter = rules()
  adapter.commitMove("e2e4")
  const before = adapter.fen()
  assert.equal(adapter.loadFen("invalid").code, "INVALID_FEN")
  assert.equal(adapter.fen(), before)
  assert.equal(adapter.loadPgn("[not valid").code, "INVALID_PGN")
  assert.equal(adapter.fen(), before)
})

test("PGN round trip preserves headers and final position", () => {
  const adapter = rules()
  assert.equal(adapter.setHeader("Event", "Omarchy Chess").ok, true)
  assert.equal(adapter.setHeader("White", "Local White").ok, true)
  assert.equal(adapter.setHeader("Unsafe", "line\n\"quoted\"").ok, true)
  for (const move of ["e2e4", "e7e5", "g1f3", "b8c6"])
    assert.equal(adapter.commitMove(move).ok, true)
  const document = adapter.pgn()
  assert.match(document, /\[Event "Omarchy Chess"\]/)
  assert.doesNotMatch(document, /line\n/)

  const restored = RulesAdapter.create({ pgn: document, pgnOptions: { strict: true } })
  assert.equal(restored.valid, true, restored.error?.detail)
  assert.equal(restored.fen(), adapter.fen())
  assert.deepEqual(restored.history({ format: "uci" }), adapter.history({ format: "uci" }))
  assert.equal(restored.getHeaders().Event, "Omarchy Chess")
})

test("clones are independent", () => {
  const adapter = rules()
  adapter.commitMove("e2e4")
  const clone = adapter.clone()
  assert.equal(clone.fen(), adapter.fen())
  clone.commitMove("e7e5")
  assert.notEqual(clone.fen(), adapter.fen())
  assert.deepEqual(adapter.history({ format: "uci" }), ["e2e4"])
})

test("generated QML artifact matches the published CommonJS oracle", () => {
  const adapter = rules("r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1")
  const oracle = new Upstream.Chess(adapter.fen())
  const actual = adapter.legalMoves({ verbose: false }).sort()
  const expected = oracle.moves({ verbose: true })
    .map((move) => move.from + move.to + (move.promotion || ""))
    .sort()
  assert.deepEqual(actual, expected)
  assert.equal(adapter.perft(3), oracle.perft(3))
})
