#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
vendor_root="$project_root/third_party/chess.js"
source_file="$vendor_root/upstream/dist/esm/chess.js"
output_file="$vendor_root/qml/chess.js"
expected_source_sha="76c7c34f0e2e9ab076521a5d6fe786a9cce537bb1b6f29d32a9c9970b5b232d2"
check_only=false

if [[ "${1:-}" == "--check" ]]; then
  check_only=true
elif [[ $# -gt 0 ]]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

if [[ ! -f "$source_file" ]]; then
  echo "error: missing pinned chess.js source: $source_file" >&2
  exit 1
fi

actual_source_sha="$(sha256sum "$source_file" | cut -d ' ' -f 1)"
if [[ "$actual_source_sha" != "$expected_source_sha" ]]; then
  echo "error: chess.js source hash mismatch" >&2
  echo "expected: $expected_source_sha" >&2
  echo "actual:   $actual_source_sha" >&2
  exit 1
fi

temporary_file="$(mktemp "$vendor_root/qml/.chess.js.XXXXXX")"
trap 'rm -f "$temporary_file"' EXIT

{
  printf '%s\n' \
    '// Generated from chess.js 1.4.0 (BSD-2-Clause).' \
    '// Source commit: ce1ff9e9fc342984ff75ca475ab39f37888cb28a' \
    '// Do not edit this file; run scripts/build-chess-vendor.sh.' \
    '' \
    'function qmlObjectFromEntries(entries) {' \
    '  var output = {}' \
    '  for (var index = 0; index < entries.length; index += 1)' \
    '    output[entries[index][0]] = entries[index][1]' \
    '  return output' \
    '}' \
    '' \
    'function qmlFlatOne(values) {' \
    '  var output = []' \
    '  for (var index = 0; index < values.length; index += 1)' \
    '    output = output.concat(values[index])' \
    '  return output' \
    '}' \
    ''
  sed \
    -e '/^const MASK64 =/,/^const SIDE_KEY = rand();$/c\
function xoroshiro128(seed) {\
    let state = Number(seed) >>> 0;\
    return function () {\
        state ^= state << 13;\
        state ^= state >>> 17;\
        state ^= state << 5;\
        return state >>> 0;\
    };\
}\
const rand = xoroshiro128(0x6b102e01);\
const PIECE_KEYS = Array.from({ length: 2 }, () => Array.from({ length: 6 }, () => Array.from({ length: 128 }, () => rand())));\
const EP_KEYS = Array.from({ length: 8 }, () => rand());\
const CASTLING_KEYS = Array.from({ length: 16 }, () => rand());\
const SIDE_KEY = rand();' \
    -e 's/0n/0/g' \
    -e 's/Object\.fromEntries/qmlObjectFromEntries/g' \
    -e 's/moves\.flat()/qmlFlatOne(moves)/g' \
    -e '/^class Move {$/i\
const QML_MOVE_FLAGS = { NORMAL: "n", CAPTURE: "c", BIG_PAWN: "b", EP_CAPTURE: "e", PROMOTION: "p", KSIDE_CASTLE: "k", QSIDE_CASTLE: "q", NULL_MOVE: "-" };\
const QML_MOVE_BITS = { NORMAL: 1, CAPTURE: 2, BIG_PAWN: 4, EP_CAPTURE: 8, PROMOTION: 16, KSIDE_CASTLE: 32, QSIDE_CASTLE: 64, NULL_MOVE: 128 };' \
    -e 's/for (const flag in BITS)/for (const flag in QML_MOVE_BITS)/g' \
    -e 's/BITS\[flag\] \& flags/QML_MOVE_BITS[flag] \& flags/g' \
    -e 's/this\.flags += FLAGS\[flag\]/this.flags += QML_MOVE_FLAGS[flag]/g' \
    -e 's/this\.flags\.indexOf(FLAGS\[/this.flags.indexOf(QML_MOVE_FLAGS[/g' \
    -e '/^    \(color\|from\|to\|piece\|captured\|promotion\|flags\|san\|lan\|before\|after\);$/d' \
    -e '/^    _\(board\|turn\|header\|kings\|epSquare\|halfMoves\|moveNumber\|history\|comments\|castling\|hash\|positionCount\) = /d' \
    -e '/^    constructor(fen = DEFAULT_POSITION, { skipValidation = false } = {}) {$/a\
        this._board = new Array(128);\
        this._turn = WHITE;\
        this._header = {};\
        this._kings = { w: EMPTY, b: EMPTY };\
        this._epSquare = -1;\
        this._halfMoves = 0;\
        this._moveNumber = 0;\
        this._history = [];\
        this._comments = {};\
        this._castling = { w: 0, b: 0 };\
        this._hash = 0;\
        this._positionCount = new Map();' \
    -e '/^const HEADER_TEMPLATE = {$/,/^};$/c\
const HEADER_TEMPLATE = Object.assign({}, SEVEN_TAG_ROSTER, SUPLEMENTAL_TAGS);' \
    -e 's/{ \.\.\.HEADER_TEMPLATE }/Object.assign({}, HEADER_TEMPLATE)/g' \
    -e '/^export { .* };$/d' \
    -e '/^\/\/# sourceMappingURL=/d' \
    "$source_file"
  printf '%s\n' \
    '' \
    'function createChess(fen) {' \
    '  return fen ? new Chess(fen) : new Chess()' \
    '}' \
    '' \
    'function validateFenValue(fen) {' \
    '  return validateFen(fen)' \
    '}' \
    '' \
    'function defaultPosition() {' \
    '  return DEFAULT_POSITION' \
    '}' \
    '' \
    'var ChessJs = {' \
    '  createChess: createChess,' \
    '  validateFen: validateFenValue,' \
    '  defaultPosition: defaultPosition' \
    '}' \
    '' \
    'if (typeof module !== "undefined" && module.exports)' \
    '  module.exports = ChessJs'
} > "$temporary_file"

chmod 0644 "$temporary_file"
if [[ -f "$output_file" ]] && cmp -s "$temporary_file" "$output_file"; then
  exit 0
fi
if [[ "$check_only" == true ]]; then
  echo "error: generated chess.js QML artifact is stale" >&2
  exit 1
fi
mv "$temporary_file" "$output_file"
